version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(package)'
      include: 'scope'
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
